name: pluc
description: "Modular cross-platform life management application"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  drift: ^2.7.0
  drift_flutter: ^2.7.0
  path_provider: ^2.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.7.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  # localization
  assets:
    - lib/l10n/

  # to generate localization
  localization:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    preferred-supported-locales:
      - en
      - es
      - ca
